ARG RUST_VERSION=1.83.0

FROM mcr.microsoft.com/windows/servercore:ltsc2022 AS build

RUN powershell -Command \
    Invoke-WebRequest -Uri https://github.com/clang/llvm-project/releases/download/llvmorg-13.0.0/LLVM-13.0.0-win64.exe -OutFile llvm.exe; \
    Start-Process -Wait -FilePath llvm.exe -ArgumentList '/SILENT'; \
    Remove-Item llvm.exe; \
    curl.exe -sSf https://sh.rustup.rs -o rustup-init.exe && \
    .\rustup-init.exe -y --default-toolchain ${RUST_VERSION} && \
    setx PATH "%PATH%;C:\Users\ContainerAdministrator\.cargo\bin"

COPY . .

CMD ["cmd", "/c", "cargo test -- --nocapture"]