ARG RUST_VERSION=1.83.0

FROM freebsd:13.2-release AS build

RUN pkg update && \
    pkg install -y clang lld git rust && \
    rustup install ${RUST_VERSION}

COPY . .

CMD ["cargo", "test", "--", "--nocapture"]
