ARG RUST_VERSION=1.83.0

FROM macos:base AS build

RUN xcode-select --install && \
    brew install llvm git && \
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain ${RUST_VERSION}

COPY . .

CMD ["cargo", "test", "--", "--nocapture"]
